### ISSUE TITLE
Bakkesmod Predicator Plugin

### ISSUE THREAD

**Issue by MarlBurroW** [samuelpmish/RLUtilities#41]
Hi, I use your lib to generate ball prediction on a minimap, and I noticed the prediction is often very different than the Predicator Bakkesmod plugin.
Does this [plugin](https://github.com/bakkesmodorg/BakkesMod2-Plugins/blob/master/BallPredictionPlugin/BallPredictionPlugin.cpp) use your [work](https://github.com/samuelpmish/RLUtilities/blob/develop/src/simulation/ball.cc)?  Or does bakkesmod use directly the game engine to predict the trajectory ?

**Comment by samuelpmish** [comment]
A few years ago, Bakkes added this library to Bakkesmod to provide the ball predictions. I'm not sure what is currently used for the predictions, but I'd guess it's still based on this code.

two potential sources of differences are:
- small changes in RLUtilities' implementation of physics model since it was integrated into Bakkesmod
- different choices of parameters (e.g. timestep)

**Comment by MarlBurroW** [comment]
Hi, thanks for your answer.
I don't think the physics has changed, my guess is I do something wrong.

If you watch my video, you'll notice that on the minimap, the trajectory changes a lot as the ball progresses, whereas in bakkesmod, the trajectory remains fairly stable over time.
Do you recognize this behavior of unstable trajectory? Or is your simulation supposed to be stable like on bakkesmod?

https://github.com/samuelpmish/RLUtilities/assets/3024430/0494b986-74a2-408f-823b-d8d40a8e1466


In the BallInfo structure, do you use something else than Physics Vectors (location, velocity, rotation, angular_velocity) to compute the simulation ? Because I don't provide any more values to create the BallInfo.

```python
   # Used to create a BallInfo structure from my custom ball class (BallInfo is not entirely filled)
    def ball_to_ballinfo(self, ball: Ball) -> BallInfo:
        ball_info = BallInfo()
        ball_info.physics.location = self.fvector_to_vector3(ball.get_location())
        ball_info.physics.velocity = self.fvector_to_vector3(ball.get_velocity())
        ball_info.physics.rotation = self.frotator_to_rotator(ball.get_rotation())
        ball_info.physics.angular_velocity = self.fvector_to_vector3(ball.get_angular_velocity())
        return ball_info
```

**Comment by samuelpmish** [comment]
From the links you included in the original post, it would seem bakkesmod is still using this library for its predictions, so there must be some inconsistency between how you're using the current library and what Bakkesmod is doing.

However, I haven't really worked on this project for several years, so I can't really help you try and explain what might be the source of the differences. I recommend that you pose your questions to the RLBot community discord channel for help, since they are more responsive and active.
